// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  description: "Fake package manager",
  subcommands: [
    {
      name: "install",
      description: "install one or more packages",
      options: [
        { name: ["-h", "--help"], description: "display help for command" },
      ],
      args: [{ name: "name", isOptional: true }],
    },
    {
      name: "search",
      description: "search with optional query",
      options: [
        { name: ["-h", "--help"], description: "display help for command" },
      ],
      args: [{ name: "query", isOptional: true }],
    },
    {
      name: "help",
      description: "display help for command",
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    { name: ["-V", "--version"], description: "output the version number" },
    { name: ["-h", "--help"], description: "display help for command" },
  ],
};

export default completionSpec;
