// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  subcommands: [
    {
      name: "brew",
      subcommands: [
        {
          name: "tea",
          options: [
            { name: ["-h", "--help"], description: "display help for command" },
          ],
        },
        {
          name: "coffee",
          options: [
            { name: ["-h", "--help"], description: "display help for command" },
          ],
        },
        {
          name: "help",
          description: "display help for command",
          args: { name: "command", isOptional: true },
        },
      ],
      options: [
        { name: ["-h", "--help"], description: "display help for command" },
      ],
    },
    {
      name: "heat",
      subcommands: [
        {
          name: "jug",
          options: [
            { name: ["-h", "--help"], description: "display help for command" },
          ],
        },
        {
          name: "pot",
          options: [
            { name: ["-h", "--help"], description: "display help for command" },
          ],
        },
        {
          name: "help",
          description: "display help for command",
          args: { name: "command", isOptional: true },
        },
      ],
      options: [
        { name: ["-h", "--help"], description: "display help for command" },
      ],
    },
    {
      name: "help",
      description: "display help for command",
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    { name: ["-h", "--help"], description: "display help for command" },
  ],
};

export default completionSpec;
