// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "program",
  subcommands: [
    {
      name: "serve",
      options: [
        {
          name: ["-t", "--trace"],
          description: "display extra information when run command",
        },
        {
          name: ["-p", "--port"],
          description: "port number",
          args: { name: "number" },
        },
        { name: ["-h", "--help"], description: "display help for command" },
      ],
      args: [{ name: "params", isOptional: true, isVariadic: true }],
    },
    {
      name: "build",
      options: [
        {
          name: ["-t", "--trace"],
          description: "display extra information when run command",
        },
        { name: ["-h", "--help"], description: "display help for command" },
      ],
      args: [{ name: "target" }],
    },
    {
      name: "help",
      description: "display help for command",
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    { name: ["-v", "---verbose"] },
    { name: ["-h", "--help"], description: "display help for command" },
  ],
};

export default completionSpec;
