// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  subcommands: [
    {
      name: "child",
      options: [
        { name: ["--gender"], description: "specific gender of child" },
        { name: ["-c", "--HELP"], description: "custom help message" },
      ],
    },
    {
      name: "help",
      description: "display help for command",
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    { name: ["-s", "--sessions"], description: "add session support" },
    {
      name: ["-t", "--template"],
      description: "specify template engine (jade|ejs) [jade]",
      args: { name: "engine", default: "jade" },
    },
    { name: ["-c", "--HELP"], description: "custom help message" },
  ],
};

export default completionSpec;
