// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    { name: ["-h", "--help"], description: "display help for command" },
  ],
  args: [{ name: "drink-size", description: "drink cup size" }],
};

export default completionSpec;
